name: HealthPlugin
main: com.fsscripts.bentzilla.Health
version: 1.0
website: http://forums.bukkit.org
authors:
  - bentzilla
description: Various Health Mods
commands:
  hp:
    description: Main HealthPlugin Command
    usage: |
           /hp chathealth <rpgstyle>